# Default FreeBSD loader.conf
# System Default Settings

bootfile="kernel"
exec="echo Loading JurkOS FreeBSD Kernel..."
kernel="kernel"
kernels="kernel"
kernels_autodetect="YES"

# Filesystem settings
vfs.root.mountfrom="ext2fs:/dev/diskid/0x12345678s1"
ext2fs_load="YES"
