# JurkOS FreeBSD Kernel Loader Configuration
# Copyright (c) 2026 AmineTheJurk

vfs.root.mountfrom="ext2fs:/dev/diskid/0x12345678s1"
kern.geom.label.disk_ident.enable="1"
kern.geom.label.gptid.enable="1"
diskid="0x12345678"
autoboot_delay="3"
ext2fs_load="YES"
