UI menu.c32
PROMPT 0
TIMEOUT 50
DEFAULT autodetect

MENU TITLE JurkOS Boot Loader
MENU COLOR border       30;44   #40ffffff #a0000000 std
MENU COLOR title        1;36;44 #9033b5e5 #a0000000 std
MENU COLOR sel          7;37;40 #e0ffffff #20ffffff all
MENU COLOR unsel        37;44   #50ffffff #a0000000 std
MENU COLOR help         37;40   #c0ffffff #a0000000 std
MENU COLOR timeout_msg  37;40   #80ffffff #00000000 std
MENU COLOR timeout      1;37;40 #c0ffffff #00000000 std
MENU COLOR msg07        37;40   #90ffffff #a0000000 std

LABEL autodetect
    MENU LABEL ^Auto-Detect CPU & Boot JurkOS (Recommended)
    MENU DEFAULT
    COM32 ifcpu64.c32
    APPEND JurkOS64 -- JurkOS32

LABEL JurkOS64
    MENU LABEL JurkOS (64-bit Kernel)
    LINUX /boot/extlinux/kernel-x86-64
    APPEND root=PARTUUID=12345678-01 rootwait rw init=/sbin/main console=ttyS0 console=tty0

LABEL JurkOS32
    MENU LABEL JurkOS (32-bit Kernel)
    LINUX /boot/extlinux/kernel-x86
    APPEND root=PARTUUID=12345678-01 rootwait rw init=/sbin/main console=ttyS0 console=tty0

LABEL reboot
    MENU LABEL ^Reboot System
    COM32 reboot.c32

LABEL poweroff
    MENU LABEL ^Power Off System
    COM32 poweroff.c32
